[general]
framerate = 30
bars = 48
autosens = 1
sensitivity = 100

[input]
method = pipewire
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = binary
bit_format = 8bit
channels = mono
