background_opacity 0.7
font_size 7
font_family JetBrains Mono
window_padding_width 10
allow_remote_control yes

# Cursor
cursor_shape beam
cursor_blink_interval 0.7
cursor_stop_blinking_after 0
cursor_trail 4
